[build]
  publish = "."

[[redirects]]
  from = "/sitemap.xml"
  to = "https://rongarland.com/sitemap.xml"
  status = 200
  force = true

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "no-cache"
