[build]
  publish = "."
  command = ""  # Keeping empty if there’s no build process

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/test-file.txt"
  to = "/test-file.txt"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://rongarland.comeyre.com"
  status = 301
  force = true  # Ensures all requests are redirected, even if Netlify thinks they should be served locally

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
  Content-Type = "application/xml"

[[headers]]
  for = "/test-file.txt"
  [headers.values]
  Content-Type = "text/plain"
